
module.exports = {
  registerUrl: 'https://forms.gle/NarTyJAMWKyfY71aA',
  dday: '2021-05-23 21:00:00',
  meets: [
    { title: 'Long-term DODO', image: '/posters/dodo_longterm.jpg' },
    { title: 'DODO19', image: '/posters/dodo19.gif' },
    { title: 'DODO18', image: '/posters/dodo18.png' },
    { title: 'DODO17', image: '/posters/dodo17.gif' },
    { title: 'DODO16', image: '/posters/dodo16.png' },
    { title: 'DODO15', image: '/posters/dodo15.png' },
    { title: 'DODO14', image: '/posters/dodo14.jpg' },
    { title: 'DODO in 강릉', image: '/posters/dodo_gl.jpg' },
    { title: 'DODO13', image: '/posters/dodo13.jpg' },
    { title: 'DODO12', image: '/posters/dodo12.jpg' },
    { title: 'DODO11', image: '/posters/dodo11.gif' },
    { title: 'DODO10', image: '/posters/dodo10.jpg' },
    { title: 'DODO9', image: '/posters/dodo9.jpg' },
    { title: 'DODO8', image: '/posters/dodo8.jpg' },
    { title: 'DODO7', image: '/posters/dodo7.jpg' },
    { title: 'DODO6', image: '/posters/dodo6.jpg' },
    { title: 'DODO5', image: '/posters/dodo5.jpg' },
    { title: 'DODO4', image: '/posters/dodo4.png' },
    { title: 'DODO3', image: '/posters/dodo3.jpg' },
  ],
}
